# Generated by Django 3.0.6 on 2020-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courbevoie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='num_tel',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
